### ISSUE TITLE
Curso Lógica de Programação

### ISSUE THREAD

**Issue by almenz1973** [cidacastello/curso-logica-programacao#1]
Começo aqui...

**Comment by cidacastello** [comment]
Que bom

**Comment by luiz086** [comment]
Olá comecei o curso obrigado pela oportunidade

**Comment by anderdeveloper85** [comment]
Olá professora, tudo bem? Espero que sim.
Eu gostaria de agradecer a senhora por disponibilizar esse conteúdo maravilhoso. A sua didática é simplesmente a melhor!
Eu fiquei em dúvida se o meu o meu algoritmo está correto. Sei que a senhora não corrige exercícios, contudo, este algoritmo está no mínimo curioso. Segue: 



algoritmo "CONSUMO DE COMBUSTÍVEL"
var
km: real
litro:real
consumo:real

inicio
     Escreval("=====================")
       Escreval("Cálculo de consumo")
      Escreval("=====================")

//km <- 350
//litro <- 35

//km <- 285.32
//litro <- 23,22

Escreval("Informe km:")
Leia (km)
Escreval ("Informe quantidade de litros:")
Leia (litro)

//Exemplo do exercício usando (EXP):
consumo <- (km*litro)/ exp (litro ,2)

//Exemplo do exercício sem usar (EXP):
//consumo <-  (km*litro)/ litro^2

Escreval("O consumo de litro por km/l é:")
Escreval(consumo:2:1)

//Caso copie o algoritmo para testar;
//Não esquecer de cancelar uma das saídas de dados.

 Escreval("=======================")
  Escreval("CONCLUÍDO COM SUCESSO")
 Escreval("=======================")

fimalgoritmo
